AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Go Music App

Resources:
  MusicFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures: [arm64]
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          # Set variables to trigger Lambda mode in your code
          GIN_MODE: release
          REGION: "ap-east-1"
          BUCKET: "lambda88-ap-east-1"
          S3_PREFIX: "httpv2/"
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
    Metadata:
      BuildMethod: makefile

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
